/*
========================================
COLOUR MAPPING
========================================
* Maps to the "Colour Mapping" presentation node (docs/nodes/node-model-specification.md):
* turns a discrete index (tile parity, Voronoi cell, ...) into an output tone.
* tones[0] = background (1), tones[last] = dark (-1), evenly spaced in between.
*
* Supports 2-5 tones, generated by formula above "3" so any count in range
* works without a new hardcoded entry; "2"/"3" stay explicit so their exact
* values can't drift if the formula changes.
*/
const TONES = {
   "2": [1, -1],
   "3": [1, 0, -1],
};

export function toneSet(tones) {
   if (TONES[tones]) return TONES[tones];
   const n = Math.round(Number(tones));
   if (Number.isFinite(n) && n >= 2 && n <= 5) {
      return Array.from({ length: n }, (_, i) => 1 - (2 * i) / (n - 1));
   }
   return TONES["2"];
}

// Maps a concentric band index (0 = the defining line, 1, 2, ... = echoes)
// to a tone: band 0 always gets the darkest declared tone, every other
// tone cycles through the remaining bands, so 4-5 declared tones read as
// an actual ring gradient. Shared by islamic.js and islamic-svg.js.
export function bandTone(shades, bandIndex) {
   if (bandIndex === 0 || shades.length < 3) return shades[shades.length - 1];
   const echoTones = shades.slice(1, shades.length - 1);
   return echoTones[(Math.abs(bandIndex) - 1) % echoTones.length];
}

// Greyscale-by-default, user-overridable fill colours for tones/colourN
// params — shared by every SVG generator that draws tone-indexed shapes
// (islamic-svg.js, grid-svg.js, voronoi-svg.js, escher-svg.js) so each
// doesn't keep its own copy of the same ramp/slicing logic.
export const DEFAULT_COLOURS = ["#ffffff", "#bfbfbf", "#808080", "#404040", "#000000"];

export function svgFillsFor(tones, slots) {
   const n = Math.max(2, Math.min(5, Math.round(Number(tones)) || 2));
   return slots.slice(0, n).map((c, i) => c ?? DEFAULT_COLOURS[i]);
}

// #rgb or #rrggbb -> {r, g, b} (0-255 each). Shared hex/RGB primitive
// behind mixHex below and render.js's raster colour mapping.
export function hexToRgb(hex) {
   const h = hex.replace("#", "");
   const full = h.length === 3 ? h.split("").map((c) => c + c).join("") : h;
   const n = parseInt(full, 16);
   return { r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255 };
}

// Linear RGB interpolation between two hex colours (t=0 -> hexA, t=1 -> hexB).
// Shared by render.js's mapColour and wave-svg.js's gradient stops/ring fills.
export function mixHex(hexA, hexB, t) {
   const a = hexToRgb(hexA), b = hexToRgb(hexB);
   const mix = (x, y) => Math.round(x + (y - x) * t);
   const toHex = (v) => v.toString(16).padStart(2, "0");
   return `#${toHex(mix(a.r, b.r))}${toHex(mix(a.g, b.g))}${toHex(mix(a.b, b.b))}`;
}
