/*
========================================
COLOUR MAPPING
========================================
* Maps to the "Colour Mapping" presentation node (docs/nodes/node-model-specification.md):
* turns a discrete index (tile parity, Voronoi cell, ...) into an output tone.
* tones[0] = background (1), tones[last] = dark (-1), evenly spaced in between.
*
* Supports 2-5 tones — generated by formula rather than hand-listed past
* "3" so a generator can offer any count in that range without this file
* growing a new hardcoded entry per count. "2" and "3" are still listed
* explicitly rather than going through the same formula, only so their
* exact values (a plain +-1 and a true 0 midpoint) can't drift if the
* formula above them ever changes.
*/
const TONES = {
   "2": [1, -1],
   "3": [1, 0, -1],
};

export function toneSet(tones) {
   if (TONES[tones]) return TONES[tones];
   const n = Math.round(Number(tones));
   if (Number.isFinite(n) && n >= 2 && n <= 5) {
      return Array.from({ length: n }, (_, i) => 1 - (2 * i) / (n - 1));
   }
   return TONES["2"];
}

// Maps a concentric "band" index (0 = the one defining line — e.g. a
// rosette medallion's own edge — 1, 2, 3, ... = successive echoes out or
// in) to one of a tone set from toneSet() above. tones[0] (the
// background) is never picked for a line; tones[last] (the darkest) is
// reserved for band 0; every other declared tone cycles through the
// remaining bands, so declaring 4 or 5 tones reads as an actual gradient
// of rings rather than only ever the same two colours regardless of how
// many were declared. Shared rather than duplicated per generator so any
// radial-banding generator gets the same behaviour for free — currently
// islamic.js and islamic-svg.js.
export function bandTone(shades, bandIndex) {
   if (bandIndex === 0 || shades.length < 3) return shades[shades.length - 1];
   const echoTones = shades.slice(1, shades.length - 1);
   return echoTones[(Math.abs(bandIndex) - 1) % echoTones.length];
}

// Greyscale-by-default, user-overridable fill colours for an SVG renderer's
// tones/colourN params (patternRegistry.js's `control: "color"` slots) —
// shared by every SVG generator that draws discrete tone-indexed shapes
// (islamic-svg.js, grid-svg.js, voronoi-svg.js, escher-svg.js) rather than
// each keeping its own copy of the same ramp and slicing logic. A
// monotonic white-to-black ramp keeps "slot 0 = background, last active
// slot = darkest/primary" true by default for any tones count from 2 to 5
// without special-casing any of them — see islamic-svg.js's original
// header comment (this was extracted from there, unchanged, once a second
// SVG generator needed the identical logic). Once a user edits any slot
// this guarantee is theirs to keep or break, same as any other choice.
export const DEFAULT_COLOURS = ["#ffffff", "#bfbfbf", "#808080", "#404040", "#000000"];

export function svgFillsFor(tones, slots) {
   const n = Math.max(2, Math.min(5, Math.round(Number(tones)) || 2));
   return slots.slice(0, n).map((c, i) => c ?? DEFAULT_COLOURS[i]);
}

// #rgb or #rrggbb -> {r, g, b} (0-255 each). Shared hex/RGB primitive
// behind mixHex below and render.js's raster colour mapping.
export function hexToRgb(hex) {
   const h = hex.replace("#", "");
   const full = h.length === 3 ? h.split("").map((c) => c + c).join("") : h;
   const n = parseInt(full, 16);
   return { r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255 };
}

// Linear RGB interpolation between two hex colours: t = 0 -> hexA,
// t = 1 -> hexB. Shared by every colour-gradient reading of a continuous
// scalar (render.js's mapColour for raster patterns; wave-svg.js's
// gradient stops and ring fills) — one interpolation primitive, not a
// separate implementation per renderer.
export function mixHex(hexA, hexB, t) {
   const a = hexToRgb(hexA), b = hexToRgb(hexB);
   const mix = (x, y) => Math.round(x + (y - x) * t);
   const toHex = (v) => v.toString(16).padStart(2, "0");
   return `#${toHex(mix(a.r, b.r))}${toHex(mix(a.g, b.g))}${toHex(mix(a.b, b.b))}`;
}
