/*
========================================
FEATURED GALLERY
========================================
* Hand-curated favourite outputs, each loadable with one click via App.jsx's
* handleLoadGalleryItem (same {entryId, overrides} -> full-params merge
* pattern proven by evaluation/quizPatterns.js).
*
* To add an entry:
*   1. Pick a pattern + params in the running app.
*   2. Select the Render node, click Export PNG (this also downloads a
*      matching {entryId, params} .json sidecar — keep it, it's the exact
*      record of what you set).
*   3. Drop the PNG into src/app/public/gallery/ (served at /gallery/... by
*      Vite's public dir).
*   4. Add an entry below: entryId + overrides copied from the sidecar json,
*      thumbnail pointing at the file from step 3.
*
* Order is deliberately curated (not grouped by entryId/pattern family) so
* browsing the gallery doesn't hit a long run of the same pattern type -
* keep new entries spread out the same way rather than appending them as a
* block. islamic-rosette entries especially (the largest family, 11 of 24)
* are kept non-adjacent throughout — moving one islamic-rosette entry
* further down the list sometimes requires relocating a second, unrelated
* entry too just to keep a valid non-adjacent spacing, since there often
* isn't a free gap otherwise.
*
* The entries below were imported from dissertation/screenshots/gallery
* outputs/ - files with a matching sidecar .json (added to export.js after
* several of these were first created) were imported with exact params;
* some others were re-exported from the app afterward to backfill a
* sidecar. A few plain screenshots in that folder aren't pattern exports
* at all and were left out. A handful of entries (marked inline) are
* approximate recreations tuned by eye + colour-sampling against an
* original export that predated the sidecar JSON, rather than exact
* reproductions.
*/

export const GALLERY_PATTERNS = [
   {
      id: "perlin-sierpinski-acid",
      title: "Acid Splat",
      description: "A shallow, single-octave warp of the Sierpinski hybrid in acid green and hot pink.",
      entryId: "perlin-sierpinski",
      overrides: {
         depth: 4,
         amplitude: 0.5,
         scale: 0.05,
         octaves: 1,
         colour1: "#c4f024",
         colour2: "#f31273",
         seed: 1337,
      },
      thumbnail: "/gallery/perlin-sierpinski-acid.png",
   },
   {
      id: "islamic-rosette-emerald-hex-bloom",
      title: "Emerald Hex Bloom",
      description: "Hexagon tiles with a green starburst centre, webbed together in gold.",
      entryId: "islamic-rosette",
      overrides: {
         tileShape: "hexagon",
         tones: "4",
         colour1: "#05665a",
         colour2: "#6cc94a",
         colour3: "#f5c414",
         colour4: "#ffffff",
         colour5: "#2dcce1",
         tileSize: 49.6,
         scale: 0.2868,
         segments: 8,
         frequency: 1,
         lineWidth: 0.0744,
         rotation: 0,
      },
      thumbnail: "/gallery/islamic-rosette-emerald-hex-bloom.png",
   },
   {
      id: "perlin-noise-teal",
      title: "Deep Teal Clouds",
      description: "A darker, low-persistence Perlin pass producing moody teal cloud cover.",
      entryId: "perlin-noise",
      overrides: {
         mode: "standard",
         scale: 0.00933,
         octaves: 4,
         lacunarity: 2,
         persistence: 0.26,
         colour1: "#0ca1ac",
         colour2: "#261b2c",
         seed: 1337,
      },
      thumbnail: "/gallery/perlin-noise-teal.png",
   },
   {
      id: "islamic-rosette-overlook-diamonds",
      title: "Overlook Diamonds",
      description: "Nested orange-and-crimson diamonds on a warm umber ground.",
      entryId: "islamic-rosette",
      overrides: {
         tileShape: "square",
         tones: "3",
         colour1: "#493127",
         colour2: "#9d0b0b",
         colour3: "#da6110",
         colour4: "#ffffff",
         colour5: "#2dcce1",
         tileSize: 99.2,
         scale: 0.354,
         segments: 4,
         frequency: 1,
         lineWidth: 0.15,
         rotation: 0,
      },
      thumbnail: "/gallery/islamic-rosette-terracotta-diamonds.png",
   },
   {
      id: "voronoi-cells-patchwork",
      title: "Voronoi Patchwork",
      description: "Five-tone Voronoi cells in a warm terracotta-and-lilac palette.",
      entryId: "voronoi-cells",
      overrides: {
         numCells: 51.5,
         tones: "5",
         colour1: "#e7f5e0",
         colour2: "#d8c2e0",
         colour3: "#5fafbf",
         colour4: "#8a3d3d",
         colour5: "#ce721c",
         seed: 1337,
      },
      thumbnail: "/gallery/voronoi-cells.png",
   },
   {
      id: "voronoi-islamic-rosettes",
      title: "Voronoi Rosettes",
      description: "Islamic radial rosettes seeded onto Voronoi cells, in pink and crimson.",
      entryId: "voronoi-islamic",
      overrides: {
         numCells: 14.75,
         tones: "5",
         colour1: "#f2bace",
         colour2: "#f4f1f1",
         colour3: "#e6476f",
         colour4: "#da3f0b",
         colour5: "#cf2075",
         segments: 6,
         scale: 0.3764,
         frequency: 4,
         lineWidth: 0.073,
         rotation: 45,
         variation: 1,
         seed: 1337,
      },
      thumbnail: "/gallery/voronoi-islamic.png",
   },
   {
      id: "ridge-noise-cotton-candy",
      title: "Cotton Candy Ridge",
      description: "A softer, low-scale ridge-noise pass producing broad pink cloud-like folds.",
      entryId: "ridge-noise",
      overrides: {
         mode: "ridge",
         scale: 0.00247,
         octaves: 2,
         lacunarity: 3,
         persistence: 0.484,
         colour1: "#df84e6",
         colour2: "#f50000",
         seed: 1337,
      },
      thumbnail: "/gallery/ridge-noise-cotton-candy.png",
   },
   {
      // Approximate recreation — tuned by eye + colour sampling against an
      // original export that predated the sidecar JSON, not an exact match.
      id: "islamic-rosette-crimson-star-frame",
      title: "Crimson Star Frame",
      description: "Larger star medallions with an interlocking diamond frame, in crimson, white and gold.",
      entryId: "islamic-rosette",
      overrides: {
         tileShape: "square",
         tones: "3",
         colour1: "#c61538",
         colour2: "#ffffff",
         colour3: "#f5c518",
         colour4: "#404040",
         colour5: "#000000",
         tileSize: 129.6,
         scale: 0.3988,
         segments: 8,
         frequency: 1,
         lineWidth: 0.0156,
         rotation: 22.5,
      },
      thumbnail: "/gallery/islamic-rosette-framed-star.png",
   },
   {
      id: "escher-translation-teal",
      title: "Teal Pinwheel Tiles",
      description: "A hand-tessellating hexagon motif with a wave-bumped edge, in teal and blush tones.",
      entryId: "escher-translation",
      overrides: {
         baseShape: "hexagon",
         bumpType: "wave",
         tones: "4",
         colour1: "#dd9f98",
         colour2: "#58c2d0",
         colour3: "#6e93a6",
         colour4: "#e8c7eb",
         colour5: "#e548ab",
         tileSize: 20,
         bumpAmp: 13.73,
      },
      thumbnail: "/gallery/escher-translation.png",
   },
   {
      id: "islamic-rosette-violet-constellation",
      title: "Violet Constellation",
      description: "Dense star medallions in deep violet with cyan lattice lines and gold accents.",
      entryId: "islamic-rosette",
      overrides: {
         tileShape: "square",
         tones: "5",
         colour1: "#5d0c88",
         colour2: "#b375db",
         colour3: "#f5c414",
         colour4: "#ff0505",
         colour5: "#2dcce1",
         tileSize: 49.6,
         scale: 0.48,
         segments: 8,
         frequency: 2,
         lineWidth: 0.0198,
         rotation: 0,
      },
      thumbnail: "/gallery/islamic-rosette-violet-constellation.png",
   },
   {
      id: "brick-grid-primary",
      title: "Primary Brick",
      description: "A four-tone brick lattice in bold primary colours.",
      entryId: "brick-grid",
      overrides: {
         shape: "brick",
         tones: "4",
         colour1: "#ec1818",
         colour2: "#f9f21a",
         colour3: "#2b1cf2",
         colour4: "#009912",
         colour5: "#000000",
         tileSize: 40,
      },
      thumbnail: "/gallery/brick-grid.png",
   },
   {
      id: "islamic-rosette-frost-blossoms",
      title: "Frost Blossoms",
      description: "Pale blue flower rosettes on a rich cobalt ground.",
      entryId: "islamic-rosette",
      overrides: {
         tileShape: "square",
         tones: "4",
         colour1: "#dbf1ff",
         colour2: "#ffffff",
         colour3: "#254d9d",
         colour4: "#b8d7ff",
         colour5: "#1d0c73",
         tileSize: 67.2,
         scale: 0.3232,
         segments: 7,
         frequency: 1,
         lineWidth: 0.15,
         rotation: 25.714285714285715,
      },
      thumbnail: "/gallery/islamic-rosette-frost-rosettes.png",
   },
   {
      id: "concentric-rings-ember",
      title: "Ember Rings",
      description: "Soft concentric rings fading from deep red to burnt orange.",
      entryId: "concentric-rings",
      overrides: {
         mode: "rings",
         frequency: 0.0543,
         colour1: "#9e1010",
         colour2: "#c1692f",
      },
      thumbnail: "/gallery/concentric-rings.png",
   },
   {
      id: "islamic-rosette-cornflower-lattice",
      title: "Cornflower Lattice",
      description: "A bright cornflower-blue triangle lattice with pale octagon centres.",
      entryId: "islamic-rosette",
      overrides: {
         tileShape: "square",
         tones: "4",
         colour1: "#b8daff",
         colour2: "#ffffff",
         colour3: "#4785ff",
         colour4: "#ffffff",
         colour5: "#4785ff",
         tileSize: 83.2,
         scale: 0.48,
         segments: 8,
         frequency: 6,
         lineWidth: 0.0954,
         rotation: 22.5,
      },
      thumbnail: "/gallery/islamic-rosette-cornflower-lattice.png",
   },
   {
      id: "recursive-grid-amber",
      title: "Amber Weave",
      description: "A recursive grid subdivided three levels deep, in amber and gold.",
      entryId: "recursive-grid",
      overrides: {
         mode: "grid",
         depth: 3,
         subdivisions: 4,
         colour1: "#ffc23d",
         colour2: "#fd8e26",
      },
      thumbnail: "/gallery/recursive-grid.png",
   },
   {
      // Approximate recreation — tuned by eye + colour sampling against an
      // original export that predated the sidecar JSON, not an exact match.
      id: "islamic-rosette-diamond-mesh",
      title: "Diamond Mesh",
      description: "Nested diamond motifs in cream, blue and gold.",
      entryId: "islamic-rosette",
      overrides: {
         tileShape: "square",
         tones: "3",
         colour1: "#f8f9d6",
         colour2: "#4e86be",
         colour3: "#e3bc51",
         colour4: "#404040",
         colour5: "#000000",
         tileSize: 129.6,
         scale: 0.3204,
         segments: 4,
         frequency: 1,
         lineWidth: 0.0296,
         rotation: 0,
      },
      thumbnail: "/gallery/islamic-rosette-diamond-mesh.png",
   },
   {
      id: "escher-translation-tropical",
      title: "Tropical Bones",
      description: "A square-tile Escher tessellation with a bold bone-shaped bump, in coral, lime and magenta.",
      entryId: "escher-translation",
      overrides: {
         tileShape: "square",
         tones: "5",
         colour1: "#fd7f58",
         colour2: "#ffeeb3",
         colour3: "#f04790",
         colour4: "#fddddd",
         colour5: "#a7e633",
         tileSize: 88,
         scale: 0.48,
         segments: 8,
         frequency: 6,
         lineWidth: 0.0954,
         rotation: 22.5,
         baseShape: "square",
         bumpAmp: 10.97,
         bumpType: "wave",
      },
      thumbnail: "/gallery/escher-translation-tropical.png",
   },
   {
      id: "islamic-rosette-hex-star",
      title: "Hex Star Lattice",
      description: "Hexagon tiles with an inscribed six-point star, in cream and burnt orange.",
      entryId: "islamic-rosette",
      overrides: {
         tileShape: "hexagon",
         tones: "2",
         colour1: "#f9eed7",
         colour2: "#c36213",
         colour3: "#808080",
         colour4: "#404040",
         colour5: "#000000",
         tileSize: 72,
         scale: 0.4324,
         segments: 6,
         frequency: 1,
         lineWidth: 0.0688,
         rotation: 0,
      },
      thumbnail: "/gallery/islamic-rosette-hex-star.png",
   },
   {
      // Approximate recreation — tuned by eye + colour sampling against an
      // original export that predated the sidecar JSON, not an exact match.
      id: "perlin-sierpinski-cyan",
      title: "Tidepool Fractal",
      description: "A deep, six-level warp of the Sierpinski hybrid in cyan and cream.",
      entryId: "perlin-sierpinski",
      overrides: {
         depth: 6,
         amplitude: 0.5,
         scale: 0.02011,
         octaves: 3,
         colour1: "#d6f2ba",
         colour2: "#13a0e7",
         seed: 1337,
      },
      thumbnail: "/gallery/perlin-sierpinski-cyan.png",
   },
   {
      // Approximate recreation — tuned by eye + colour sampling against an
      // original export that predated the sidecar JSON, not an exact match.
      id: "islamic-rosette-golden-rosette-field",
      title: "Golden Rosette Field",
      description: "Densely packed nine-point star medallions in crimson and gold.",
      entryId: "islamic-rosette",
      overrides: {
         tileShape: "square",
         tones: "3",
         colour1: "#c61538",
         colour2: "#e8a530",
         colour3: "#f5d9a8",
         colour4: "#404040",
         colour5: "#000000",
         tileSize: 100.8,
         scale: 0.3008,
         segments: 9,
         frequency: 1,
         lineWidth: 0.0254,
         rotation: 0,
      },
      thumbnail: "/gallery/islamic-rosette-star-medallion.png",
   },
   {
      id: "perlin-noise-moss",
      title: "Mossy Perlin",
      description: "Classic Perlin noise rendered as a soft green, moss-like texture.",
      entryId: "perlin-noise",
      overrides: {
         mode: "standard",
         scale: 0.03677,
         octaves: 4,
         lacunarity: 3,
         persistence: 0.492,
         colour1: "#badd78",
         colour2: "#146204",
         seed: 1337,
      },
      thumbnail: "/gallery/perlin-noise.png",
   },
   {
      id: "islamic-rosette-midnight-starfield",
      title: "Midnight Starfield",
      description: "Glowing white starbursts scattered across a deep indigo night sky.",
      entryId: "islamic-rosette",
      overrides: {
         tileShape: "square",
         tones: "5",
         colour1: "#e5f4ff",
         colour2: "#0d004d",
         colour3: "#4785ff",
         colour4: "#0042c7",
         colour5: "#450c73",
         tileSize: 83.2,
         scale: 0.424,
         segments: 10,
         frequency: 1,
         lineWidth: 0.15,
         rotation: 0,
      },
      thumbnail: "/gallery/islamic-rosette-midnight-starfield.png",
   },
   {
      id: "ridge-noise-slate",
      title: "Slate Ridges",
      description: "Ridge noise rendered as a worn, leathery slate-and-tan texture.",
      entryId: "ridge-noise",
      overrides: {
         mode: "ridge",
         scale: 0.02844,
         octaves: 3,
         lacunarity: 3,
         persistence: 0.572,
         colour1: "#4b5c63",
         colour2: "#f4c299",
         seed: 1337,
      },
      thumbnail: "/gallery/ridge-noise-slate.png",
   },
   {
      id: "islamic-rosette-tudor-badge",
      title: "Tudor Badge",
      description: "Bold crimson pentagon badges with white cutout facets on charcoal.",
      entryId: "islamic-rosette",
      overrides: {
         tileShape: "hexagon",
         tones: "3",
         colour1: "#303130",
         colour2: "#c94a4a",
         colour3: "#fffefa",
         colour4: "#ffffff",
         colour5: "#2dcce1",
         tileSize: 96,
         scale: 0.48,
         segments: 5,
         frequency: 2,
         lineWidth: 0.1276,
         rotation: 36,
      },
      thumbnail: "/gallery/islamic-rosette-crimson-badge.png",
   },
];
